apiVersion: v1
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: "120"
  ADMIN_EMAIL: admin@cstrader.com
  ADMIN_NAME: System Admin
  ALGORITHM: HS256
  DATABASE_DRIVER: postgresql
  DATABASE_HOST: database
  DATABASE_NAME: db
  DATABASE_PORT: "5432"
kind: ConfigMap
metadata:
  name: backend-config
